apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-rs
  namespace: oauth
  labels:
    app: oauth
spec:
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
        - name: oauth-rs
          image: gmae199boy/oauth-rs:0.0.5
          ports:
            - containerPort: 3000
              name: oauth-port
          env:
            - name: KAKAO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: KAKAO_API_KEY
            - name: KAKAO_REDIRECT_URL
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: KAKAO_REDIRECT_URL
            - name: KAKAO_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: oauth
                  key: KAKAO_ADMIN_KEY
